from pathlib import Path
import re
p=Path('/mnt/data/work/app.py')
s=p.read_text(encoding='utf-8')
marker='\ndef resource_content(resource):\n'
assert marker in s
insert=r'''

# Expanded revision notes: these packs are deliberately richer than the short
# resource summaries. Each supported topic exposes 20+ sections with explanations,
# examples, formulas/rules and exam-oriented checks. Unknown topics use the detailed
# fallback below instead of learner-directed "write your own answer" prompts.
DETAILED_NOTES = {
    "fractions": [
        ("1. Meaning of a fraction", "A fraction represents a quantity in equal parts. The denominator tells how many equal parts make one whole, while the numerator tells how many of those parts are being considered."),
        ("2. Numerator and denominator", "In a/b, a is the numerator and b is the denominator, with b not equal to zero. The denominator defines the size of each equal part, so changing it changes the fraction's value unless the numerator changes proportionally."),
        ("3. Proper fractions", "A proper fraction has a numerator smaller than its denominator, so its value lies between 0 and 1 for positive numbers. Examples include 2/5 and 7/10."),
        ("4. Improper fractions", "An improper fraction has a numerator greater than or equal to its denominator. It can represent a value of 1 or more and can often be converted into a mixed number."),
        ("5. Mixed numbers", "A mixed number contains a whole number and a proper fraction, such as 2 3/4. To convert it to an improper fraction, multiply the whole number by the denominator, add the numerator, and keep the denominator."),
        ("6. Equivalent fractions", "Equivalent fractions have the same numerical value even though their numerator and denominator may look different. Multiplying or dividing both parts by the same non-zero number preserves the value."),
        ("7. Simplest form", "A fraction is in simplest form when the numerator and denominator have no common factor greater than 1. Divide both by their greatest common factor to simplify efficiently."),
        ("8. Comparing fractions", "For equal denominators, compare numerators directly. For different denominators, use a common denominator or cross multiplication while keeping the comparison direction consistent."),
        ("9. Fractions on a number line", "A number line makes fraction size visible. Divide the interval from 0 to 1 into the denominator's number of equal parts and count the numerator's parts from zero."),
        ("10. Addition with like denominators", "When denominators are equal, add the numerators and keep the common denominator. Simplify the result if a common factor remains."),
        ("11. Addition with unlike denominators", "Find a common denominator, usually through the LCM, convert each fraction, and then add the numerators. Adding denominators directly is not a valid method."),
        ("12. Subtraction", "Subtraction follows the same denominator rule as addition. Convert unlike denominators first, subtract the numerators, and simplify the final fraction."),
        ("13. Multiplication", "Multiply numerator by numerator and denominator by denominator. Before multiplying, cancel common factors when possible to keep the arithmetic smaller and reduce errors."),
        ("14. Division", "To divide by a fraction, multiply by its reciprocal. For a/b divided by c/d, the result is a/b multiplied by d/c, provided c is not zero."),
        ("15. Reciprocal", "The reciprocal of a non-zero fraction a/b is b/a. A non-zero number multiplied by its reciprocal gives 1, which is why reciprocals are used in fraction division."),
        ("16. Fractions and decimals", "A fraction can be converted to a decimal by dividing numerator by denominator. A terminating decimal occurs when the simplified denominator has no prime factors other than 2 and 5."),
        ("17. Fractions and percentages", "A fraction can be converted to a percentage by multiplying by 100. For example, 3/5 represents 60 percent because 3/5 × 100 = 60."),
        ("18. Negative fractions", "A negative sign may be written before the fraction or with the numerator. When multiplying or dividing, use the usual sign rules and then simplify the magnitude."),
        ("19. Word problems", "Translate phrases such as 'of', 'remaining', 'difference' and 'shared equally' into the appropriate operations. Write the quantity as a fraction before calculating and check whether the answer is reasonable."),
        ("20. Worked example", "For 1/4 + 2/3, the LCM of 4 and 3 is 12. Convert the fractions to 3/12 and 8/12, giving 11/12 after addition."),
        ("21. Estimation and checking", "Estimate the size of each fraction before calculating. A result larger than expected can reveal an operation or simplification error immediately."),
        ("22. Common mistakes", "Do not add denominators, change only one part of a fraction, or forget to simplify. During division, do not take the reciprocal of both fractions; only the divisor is inverted."),
        ("23. Exam revision strategy", "Memorize the operation rules, then practise one example of each type: simplify, compare, add, subtract, multiply, divide and convert. Finish by solving a mixed question without looking at the method."),
    ],
    "geometry": [
        ("1. Geometry vocabulary", "Geometry studies shapes, sizes, positions and relationships. Learn the meanings of point, line, ray, segment, angle, vertex, side, perimeter, area and volume before using formulas."),
        ("2. Angle types", "An acute angle is less than 90 degrees, a right angle is 90 degrees, an obtuse angle is between 90 and 180 degrees, and a straight angle is 180 degrees."),
        ("3. Complementary and supplementary angles", "Complementary angles add to 90 degrees, while supplementary angles add to 180 degrees. These relationships are often used to find a missing angle quickly."),
        ("4. Vertically opposite angles", "When two straight lines intersect, vertically opposite angles are equal. Adjacent angles on a straight line add to 180 degrees."),
        ("5. Parallel lines and transversals", "When a transversal crosses parallel lines, corresponding and alternate interior angles have useful equality relationships, while co-interior angles are supplementary."),
        ("6. Triangle classification", "Triangles can be classified by sides as scalene, isosceles or equilateral, and by angles as acute, right or obtuse. Identify the classification before selecting a property."),
        ("7. Triangle angle sum", "The interior angles of every triangle add to 180 degrees. If two angles are known, subtract their sum from 180 degrees to obtain the third."),
        ("8. Isosceles and equilateral triangles", "An isosceles triangle has two equal sides and equal opposite angles. An equilateral triangle has three equal sides and each interior angle is 60 degrees."),
        ("9. Congruence", "Congruent figures have the same shape and size. Common triangle congruence criteria include SSS, SAS and ASA/AAS, depending on the syllabus and stated information."),
        ("10. Similarity", "Similar figures have the same shape but may have different sizes. Corresponding angles are equal and corresponding lengths are in the same ratio."),
        ("11. Pythagoras theorem", "For a right triangle, the square of the hypotenuse equals the sum of the squares of the other two sides: c² = a² + b². Identify the right angle before applying the theorem."),
        ("12. Quadrilaterals", "A quadrilateral has four sides and its interior angles total 360 degrees. Rectangle, square, parallelogram, rhombus and trapezium have additional properties that distinguish them."),
        ("13. Rectangle and square", "For a rectangle, area is length × breadth and perimeter is 2(length + breadth). For a square, area is side² and perimeter is 4 × side."),
        ("14. Parallelogram", "Opposite sides of a parallelogram are parallel and equal, and opposite angles are equal. Its area is base × perpendicular height, not base multiplied by a slanted side."),
        ("15. Triangle area", "The area of a triangle is one-half × base × perpendicular height. The height must be perpendicular to the chosen base, even if it lies outside the visible triangle in some configurations."),
        ("16. Circle vocabulary", "Radius joins the centre to the circle, while diameter passes through the centre and equals twice the radius. Chord, arc, sector and circumference are related terms worth distinguishing."),
        ("17. Circle circumference", "The circumference of a circle is 2πr or πd. Use the value of π specified by the question and keep the radius and diameter distinction clear."),
        ("18. Circle area", "The area of a circle is πr². Squaring the radius is essential; using πr gives a length rather than an area."),
        ("19. Coordinate geometry", "A coordinate is written as (x, y), where x describes horizontal position and y describes vertical position. Read the axes and signs carefully before plotting a point."),
        ("20. Distance and midpoint", "For two coordinate points, distance can be found using the Pythagorean relationship on horizontal and vertical differences. The midpoint is found by averaging the two x-coordinates and the two y-coordinates."),
        ("21. Perimeter versus area", "Perimeter measures the boundary length and uses square units only when an area is being measured. Area measures the surface enclosed by a shape and is expressed in square units."),
        ("22. Diagram-first method", "Mark all known lengths and angles, identify the shape, write the relevant property or formula, substitute values and then check the units. A labelled sketch reduces many geometry mistakes."),
        ("23. Common mistakes", "Do not confuse radius with diameter, sloping length with perpendicular height, or perimeter with area. Also avoid applying a theorem without checking its conditions."),
        ("24. Exam revision strategy", "Revise properties by shape, then formulas, then mixed diagram questions. For every numerical answer, include the rule, working and correct unit."),
    ],
    "algebra": [
        ("1. Algebraic language", "An algebraic expression combines numbers, variables and operations. A term is separated from another term by plus or minus signs, while a coefficient is the numerical factor of a variable."),
        ("2. Variables and constants", "A variable represents an unknown or changing quantity, while a constant has a fixed value. In 5x + 3, x is the variable, 5 is its coefficient and 3 is the constant."),
        ("3. Terms and coefficients", "Terms such as 4x, -3y and 7 are individual parts of an expression. The sign belongs to the term, so losing a negative sign can change the entire result."),
        ("4. Like terms", "Like terms have identical variable parts and powers. Only like terms can be combined by adding or subtracting their coefficients."),
        ("5. Simplifying expressions", "Collect like terms carefully and preserve unlike terms. For example, 4x + 3x - 2 becomes 7x - 2."),
        ("6. Order of operations", "Evaluate brackets first, then powers, then multiplication or division, and finally addition or subtraction. When operations have equal priority, work from left to right."),
        ("7. Distributive property", "The distributive property multiplies an outside factor by every term inside brackets: a(b+c) = ab+ac. With subtraction, a(b-c) = ab-ac."),
        ("8. Algebraic identities", "Identities are equations true for all permitted values. Common identities include (a+b)² = a²+2ab+b² and (a-b)² = a²-2ab+b²."),
        ("9. Factorisation", "Factorisation reverses expansion by expressing an expression as a product. First look for a common factor, then use an appropriate identity or method."),
        ("10. Linear equations", "A linear equation has the variable to the first power. Isolate the variable using inverse operations and perform the same operation on both sides."),
        ("11. Equation balance", "An equation states that two expressions are equal. Any operation performed on one side must also be performed on the other side to preserve equality."),
        ("12. Equations with brackets", "Expand brackets first when helpful, combine like terms, and then isolate the variable. Check the final value by substituting it into the original equation."),
        ("13. Equations with fractions", "Clear simple fractional denominators by multiplying both sides by a suitable common denominator, while applying the operation to every term."),
        ("14. Inequalities", "Inequalities use symbols such as <, >, ≤ and ≥. When multiplying or dividing both sides by a negative number, reverse the inequality sign."),
        ("15. Simultaneous equations", "Two equations can be solved together when they contain the same unknowns. Elimination removes one variable, while substitution replaces one variable using an expression from the other equation."),
        ("16. Quadratic equations", "A quadratic equation contains a squared variable. Depending on the form, it may be solved by factorisation, completing the square or the quadratic formula."),
        ("17. Graphs", "A graph shows how values change together. For a linear relation y = mx + c, m represents the gradient and c represents the y-intercept."),
        ("18. Substitution", "Substitution means replacing a variable with a known value. Use brackets when substituting a negative number so that signs are preserved correctly."),
        ("19. Algebraic fractions", "Algebraic fractions contain variables in numerators or denominators. State restrictions where a denominator could become zero, then simplify using valid factor cancellation."),
        ("20. Worked example", "For 3x + 5 = 20, subtract 5 from both sides to obtain 3x = 15, then divide by 3 to get x = 5. Substituting 5 back gives 20 on the left, confirming the solution."),
        ("21. Translating words into algebra", "Words such as 'sum', 'difference', 'product', 'twice' and 'less than' indicate mathematical operations. Translate the statement slowly before simplifying it."),
        ("22. Common sign errors", "A negative outside a bracket changes the signs of every term inside. Keep each algebraic step on a separate line when signs are easy to lose."),
        ("23. Exam checking", "Substitute numerical solutions back into the original equation rather than only checking the last line. For inequalities and graphs, also check direction and boundary conditions."),
        ("24. Revision strategy", "Revise expressions, identities, equations, inequalities and graphs separately, then mix them. The key skill is choosing the correct method from the structure of the question."),
    ],
    "photosynthesis": [
        ("1. Definition", "Photosynthesis is the process by which green plants use light energy to make organic food from carbon dioxide and water, with oxygen released as a product under typical textbook descriptions."),
        ("2. Overall equation", "The word equation is carbon dioxide + water → glucose + oxygen. Light energy and chlorophyll are essential parts of the process, and the balanced chemical equation depends on the level of study."),
        ("3. Chloroplast", "Photosynthesis mainly occurs in chloroplast-containing cells. Chloroplasts contain chlorophyll and internal membrane systems that support the light-dependent reactions."),
        ("4. Chlorophyll", "Chlorophyll is a pigment that absorbs light energy. It allows plants to capture energy that can ultimately be stored in chemical bonds during food formation."),
        ("5. Leaf as a photosynthetic organ", "Leaves are adapted for photosynthesis by providing a large surface area and internal tissues for gas exchange and transport. Their vascular system supplies water and distributes sugars."),
        ("6. Carbon dioxide entry", "Carbon dioxide enters leaves mainly through stomata, which are pores controlled by guard cells. Stomatal opening balances gas exchange with water loss."),
        ("7. Water supply", "Roots absorb water from the soil, and xylem transports water upward to the leaves. Water acts as a raw material for photosynthesis and is also important for maintaining plant tissues."),
        ("8. Light energy", "Light provides the energy needed to drive the photosynthetic reactions. Increasing light intensity can increase the rate when light is the limiting factor, but only within suitable conditions."),
        ("9. Light-dependent reactions", "Light-dependent reactions capture light energy and involve electron transfer and the formation of energy-rich molecules. Water is involved and oxygen is released from the splitting of water in the overall process."),
        ("10. Carbon fixation", "In the carbon-fixation stage, carbon dioxide is incorporated into organic molecules through enzyme-controlled reactions. In higher-level biology, this is associated with the Calvin cycle."),
        ("11. Glucose", "Glucose is an important product because it can be used in cellular respiration, converted to starch for storage, or used as a building block for other biological molecules."),
        ("12. Oxygen", "Oxygen is released during photosynthesis and can diffuse out of the leaf. It is not the food product of photosynthesis; glucose represents the main carbohydrate product in the simplified equation."),
        ("13. Stomata and gas exchange", "Stomata provide a pathway for carbon dioxide entry and oxygen movement. Guard cells regulate the pore size in response to environmental conditions."),
        ("14. Limiting factors", "A limiting factor is a condition that restricts the rate when other requirements are available in excess. Light intensity, carbon dioxide concentration and temperature are common factors studied in school biology."),
        ("15. Effect of light intensity", "At low light intensity, increasing light generally increases the rate because more energy is available. Eventually another factor becomes limiting, so the rate no longer rises proportionally."),
        ("16. Effect of carbon dioxide", "Increasing carbon dioxide can increase the rate when carbon dioxide is limiting. Beyond a certain point, another factor limits the process and additional carbon dioxide has little effect."),
        ("17. Effect of temperature", "Photosynthesis involves enzymes, so temperature affects the reaction rate. Very low temperature slows enzyme activity, while excessive heat can disrupt enzyme structure and reduce the rate."),
        ("18. Photosynthesis versus respiration", "Photosynthesis stores energy in organic molecules using light energy, while cellular respiration releases usable energy from organic molecules. They are related but are not the same process."),
        ("19. Experimental evidence", "A classic school investigation can test starch formation in leaves after controlling light and other conditions. Iodine solution is commonly used as an indicator for starch, following the required safety and laboratory procedure."),
        ("20. Measuring rate", "The rate of photosynthesis can be estimated by measuring oxygen production, carbon dioxide uptake or changes in biomass under controlled conditions. A fair comparison changes one independent variable while controlling others."),
        ("21. Factors that can confuse results", "Leaf area, temperature, water availability, carbon dioxide concentration and previous light exposure can affect an experiment. Controls and repeated measurements improve reliability."),
        ("22. Common misconceptions", "Plants respire as well as photosynthesise. Also, sunlight is an energy source rather than a raw material, while carbon dioxide and water are raw materials in the overall equation."),
        ("23. Exam answer structure", "For a theory question, define the process, state the required conditions, explain the role of the relevant structure or factor, and finish with the expected product or effect."),
        ("24. Revision checklist", "Remember the overall equation, chloroplast/chlorophyll roles, stomata, xylem, glucose uses, oxygen release and the three major limiting factors. Then practise interpreting rate-versus-factor graphs."),
    ],
    "grammar": [
        ("1. What makes a sentence", "A complete sentence expresses a complete thought and normally contains a subject and a predicate. Sentence structure helps the reader understand who performs an action and what happens."),
        ("2. Subject", "The subject is the person, thing or idea the sentence is about. In long sentences, locate the true subject before deciding which verb form is required."),
        ("3. Predicate", "The predicate contains the verb and the information about the subject. It may be a single verb or a much longer phrase."),
        ("4. Nouns", "Nouns name people, places, objects, qualities or ideas. They may be common, proper, abstract or collective depending on the classification system being used."),
        ("5. Pronouns", "Pronouns replace or refer to nouns, helping avoid unnecessary repetition. Their form should match the intended person, number and grammatical role."),
        ("6. Verbs", "Verbs express actions, states or occurrences. The verb form changes according to tense, subject and sometimes voice or mood."),
        ("7. Subject-verb agreement", "A singular subject generally takes a singular verb in the present tense, while a plural subject takes the plural form. Ignore distracting words between the subject and verb when checking agreement."),
        ("8. Adjectives", "Adjectives describe or modify nouns and pronouns. Place them where their relationship to the intended noun is clear."),
        ("9. Adverbs", "Adverbs commonly modify verbs, adjectives or other adverbs and can express manner, time, place or degree. The exact grammatical role depends on the sentence."),
        ("10. Prepositions", "Prepositions show relationships such as place, time, direction or connection. Common examples include in, on, at, under, between and through."),
        ("11. Conjunctions", "Conjunctions connect words, phrases or clauses. Coordinating conjunctions join elements of equal status, while subordinating conjunctions introduce dependent clauses."),
        ("12. Phrases and clauses", "A phrase is a group of words functioning together without a complete subject-verb clause structure, while a clause contains a subject and a verb. Independent clauses can stand as sentences."),
        ("13. Tenses", "Tense indicates time and aspect of an action or state. Use time clues such as yesterday, now, already and tomorrow, but also check the meaning of the entire sentence."),
        ("14. Active and passive voice", "In active voice, the subject performs the action. In passive voice, the subject receives the action, and the appropriate form of 'be' plus the past participle is used."),
        ("15. Direct and indirect speech", "Direct speech reports the exact words within quotation marks, while indirect speech reports the meaning without quoting the original wording. Pronouns and tense may change when converting between forms."),
        ("16. Determiners", "Determiners help specify nouns. Articles such as a, an and the are common determiners, and other words such as this, those, some and each can serve similar functions."),
        ("17. Modals", "Modal verbs such as can, could, may, might, must, should and would express ability, possibility, permission, obligation or expectation. The following verb generally remains in its base form."),
        ("18. Punctuation", "Full stops, commas, question marks, colons, semicolons and apostrophes help organise meaning. Punctuation should reflect sentence structure rather than being inserted only where a pause sounds natural."),
        ("19. Common error detection", "Read the whole sentence before correcting an error. Check subject-verb agreement, tense, article use, prepositions, pronouns, word order and punctuation in that order."),
        ("20. Sentence transformation", "When changing a sentence from one form to another, preserve its meaning while changing the required grammatical structure. Check that no important information is lost."),
        ("21. Editing strategy", "First identify the sentence's intended meaning, then locate the grammatical unit containing the error. Make the smallest correction that produces a grammatically sound sentence."),
        ("22. Common mistakes", "Frequent errors include confusing its/it's, their/there/they're, subject-verb agreement, inconsistent tense and missing punctuation. Always judge the word by its role in the sentence."),
        ("23. Exam strategy", "For grammar questions, eliminate options that break agreement or tense before comparing the remaining choices. Read the completed sentence aloud mentally for meaning and structure."),
        ("24. Revision checklist", "Revise sentence structure, parts of speech, agreement, tenses, voice, reported speech, determiners, modals and punctuation. Practise editing complete sentences rather than isolated words."),
    ],
    "electricity": [
        ("1. Electric charge", "Electric charge is a physical property responsible for electrical interactions. Charge is measured in coulombs, and current describes the rate at which charge passes a point."),
        ("2. Electric current", "Electric current is the rate of flow of charge: I = Q/t. Its SI unit is the ampere, equivalent to coulomb per second."),
        ("3. Conventional current", "Conventional current is taken to flow from higher electric potential to lower potential in the external circuit. Electron motion in metals is opposite to the conventional current direction."),
        ("4. Potential difference", "Potential difference measures energy transferred per unit charge: V = W/Q. It is measured in volts and provides the electrical driving difference between two points."),
        ("5. Electromotive force", "The emf of a source represents the energy supplied by the source per unit charge. It is related to the source's ability to drive current in a circuit."),
        ("6. Resistance", "Resistance measures opposition to current and is measured in ohms. For an ohmic conductor under suitable constant conditions, V = IR."),
        ("7. Ohm's law", "Ohm's law states that current through an ohmic conductor is proportional to potential difference when physical conditions such as temperature remain constant. It can be rearranged as I = V/R or R = V/I."),
        ("8. Resistivity", "Resistivity is a material property that relates resistance to conductor length and cross-sectional area. For a uniform conductor, R = ρL/A."),
        ("9. Series circuits", "In a series circuit, the same current passes through each component. The equivalent resistance is the sum of individual resistances."),
        ("10. Parallel circuits", "In a parallel arrangement, each branch has the same potential difference across it, while the total current is divided among branches. Equivalent resistance is lower than the smallest branch resistance for positive resistors."),
        ("11. Electrical power", "Electrical power is the rate of electrical energy transfer. Useful forms include P = VI, P = I²R and P = V²/R when the relevant conditions apply."),
        ("12. Electrical energy", "Electrical energy transferred over time can be calculated using E = Pt. In domestic contexts, energy may be expressed in kilowatt-hours rather than joules."),
        ("13. Heating effect", "When current passes through resistance, electrical energy can be converted into thermal energy. The heating effect is important in heaters, fuses and other devices."),
        ("14. Ammeter", "An ammeter measures current and is connected in series so that the circuit current passes through the instrument. An ideal ammeter has very low resistance."),
        ("15. Voltmeter", "A voltmeter measures potential difference between two points and is connected in parallel with the component. An ideal voltmeter has very high resistance."),
        ("16. Kirchhoff's current law", "At a junction, the total current entering equals the total current leaving when charge does not accumulate at the junction. This expresses conservation of charge."),
        ("17. Kirchhoff's voltage law", "Around a closed circuit loop, the algebraic sum of potential changes is zero under the chosen sign convention. This expresses conservation of energy."),
        ("18. Cells and internal resistance", "A real cell has internal resistance, so its terminal voltage can fall when current is drawn. Distinguish the emf of the source from the terminal potential difference under load."),
        ("19. Household safety", "Fuses and circuit breakers protect circuits from excessive current. Earthing and appropriate insulation reduce the risk of electric shock, and household wiring normally uses parallel connections for independent operation."),
        ("20. Worked example", "If a 5-ohm resistor carries 2 A, Ohm's law gives V = IR = 10 V. The electrical power is then P = VI = 20 W."),
        ("21. Unit checking", "Convert milliamperes to amperes, kilowatts to watts and other prefixes before substitution. Check that the final unit matches the physical quantity requested."),
        ("22. Common mistakes", "Do not connect an ammeter in parallel or a voltmeter in series. Also distinguish current, charge, potential difference, resistance, power and energy instead of treating them as interchangeable."),
        ("23. Circuit-solving method", "Draw or simplify the circuit, identify series and parallel groups, calculate equivalent resistance, use Ohm's law and then verify current or voltage relationships at each branch."),
        ("24. Revision checklist", "Memorise I = Q/t, V = W/Q, V = IR, P = VI, series/parallel rules and instrument connections. Then practise mixed circuit problems with explicit units and sign conventions."),
    ],
    "thermodynamics": [
        ("1. Thermodynamic system", "A thermodynamic system is the part of the universe selected for study. Everything outside it is the surroundings, and the boundary separates the two."),
        ("2. Open, closed and isolated systems", "An open system can exchange matter and energy with its surroundings. A closed system can exchange energy but not matter, while an ideal isolated system exchanges neither."),
        ("3. State variables", "Pressure, volume and temperature are common state variables. A state is described by a suitable set of variables, while a process describes the change from one state to another."),
        ("4. Thermal equilibrium", "Thermal equilibrium means there is no net heat transfer between systems in thermal contact. The zeroth law provides the basis for the concept of temperature."),
        ("5. Temperature", "Temperature characterises the thermal state of a system and determines the direction of heat transfer between bodies initially at different temperatures. It is not the same physical quantity as heat."),
        ("6. Heat", "Heat is energy transferred because of a temperature difference. It is a process of energy transfer, not a substance stored inside an object."),
        ("7. Internal energy", "Internal energy is the microscopic energy associated with the constituents of a system. Its change depends on the initial and final states for a state function, even though heat and work depend on the path."),
        ("8. Work in thermodynamics", "Work is energy transfer associated with macroscopic forces and displacement. For a quasistatic expansion or compression, mechanical work is related to the area under a pressure-volume curve."),
        ("9. First law of thermodynamics", "Using W as work done by the system, the first law can be written Q = ΔU + W. It expresses conservation of energy and requires a consistent sign convention."),
        ("10. Sign convention", "Before solving a numerical problem, state whether W is work done by or on the system and how heat entering or leaving is signed. Many apparent disagreements are caused by switching conventions mid-solution."),
        ("11. Isothermal process", "An isothermal process occurs at constant temperature. For an ideal gas under suitable conditions, internal energy depends only on temperature, so the change in internal energy is zero."),
        ("12. Adiabatic process", "An adiabatic process has no heat transfer, so Q = 0. Any change in internal energy is then connected to the work interaction according to the chosen sign convention."),
        ("13. Isobaric process", "An isobaric process occurs at constant pressure. When a system expands at constant external pressure, mechanical work is related to pressure and the change in volume."),
        ("14. Isochoric process", "An isochoric process occurs at constant volume. For a simple fixed-volume system doing no boundary work, the volume-work term is zero, so heat transfer changes internal energy directly."),
        ("15. P-V diagrams", "A pressure-volume graph represents a thermodynamic path. For a quasistatic process, the area under the curve corresponds to the mechanical work with the sign determined by expansion or compression convention."),
        ("16. Reversible and irreversible processes", "A reversible process is an idealised process that can be reversed through infinitesimal changes without net changes to the surroundings. Real processes involve finite gradients, friction or other irreversibilities."),
        ("17. Second law", "The second law introduces the directionality of natural processes and limits the conversion of heat into work. It also provides the foundation for entropy and heat-engine efficiency."),
        ("18. Entropy", "Entropy is a state function associated with the direction and dispersal of energy in thermodynamic processes. For an isolated system, the total entropy does not decrease in a spontaneous irreversible process."),
        ("19. Heat engines", "A heat engine operates cyclically, taking energy from a high-temperature source, doing useful work and rejecting some energy to a lower-temperature sink. No engine can convert all input heat into work in a cyclic process."),
        ("20. Carnot engine", "The Carnot cycle is an ideal reversible cycle used as a benchmark for maximum efficiency between two temperatures. Its efficiency depends on the absolute temperatures of the hot and cold reservoirs."),
        ("21. Refrigerator", "A refrigerator uses external work to transfer heat from a colder region to a warmer environment. Its performance is described using a coefficient of performance rather than ordinary heat-engine efficiency."),
        ("22. Ideal gas connection", "For an ideal gas, pressure, volume, amount and absolute temperature are related by an equation of state. Always use kelvin for thermodynamic temperature in gas-law calculations."),
        ("23. Heat capacities", "Specific heat capacity measures the energy required per unit mass per unit temperature change. In gases, molar heat capacities at constant pressure and constant volume differ because expansion work can occur at constant pressure."),
        ("24. Worked example", "If a system receives 500 J of heat and does 200 J of work, then with W defined as work done by the system, ΔU = Q - W = 300 J. The numerical result follows directly from the stated convention."),
        ("25. Exam strategy", "Write the system and sign convention first, identify the process, list known quantities with units, choose the appropriate law, substitute carefully and check whether the direction of heat/work makes physical sense."),
    ],
    "vector": [
        ("1. What is a vector?", "A vector is a quantity that has both magnitude and direction. Examples include displacement, velocity, acceleration and force, whereas scalar quantities such as mass, time and temperature have magnitude only."),
        ("2. Scalar versus vector", "A scalar is described completely by a numerical value and unit, while a vector also requires direction. Adding vectors therefore requires attention to direction, not just their numerical magnitudes."),
        ("3. Magnitude", "The magnitude of a vector is its size or length and is a non-negative scalar. For a vector a = ai + bj + ck, its magnitude is √(a²+b²+c²)."),
        ("4. Direction", "Direction describes the orientation of a vector relative to a chosen reference. In two dimensions it may be represented by an angle, while in three dimensions direction can be represented using components or direction cosines."),
        ("5. Unit vectors", "A unit vector has magnitude 1 and indicates direction only. The standard Cartesian unit vectors are i, j and k along the x, y and z axes respectively."),
        ("6. Position vector", "The position vector of a point gives its location relative to the chosen origin. If P has coordinates (x,y,z), its position vector is xi + yj + zk."),
        ("7. Vector components", "A vector can be resolved into perpendicular components along coordinate axes. Components make addition, subtraction and many geometric calculations systematic."),
        ("8. Addition of vectors", "Vectors are added component-wise or geometrically using the triangle/parallelogram rule. The direction of the resultant must be considered along with its magnitude."),
        ("9. Subtraction", "Subtracting vector b from vector a means adding the negative of b: a-b = a+(-b). The negative vector has the same magnitude as b but the opposite direction."),
        ("10. Multiplication by a scalar", "Multiplying a vector by a positive scalar changes its magnitude, while a negative scalar also reverses its direction. A zero scalar produces the zero vector."),
        ("11. Zero vector", "The zero vector has magnitude zero and no unique direction. It acts as the additive identity because a + 0 = a."),
        ("12. Parallel and collinear vectors", "Two non-zero vectors are parallel when one is a scalar multiple of the other. Collinear points have position vectors related along the same line."),
        ("13. Section formula", "A point dividing a line segment in a specified ratio can be represented using weighted position vectors. The internal-division formula is applied only after the ratio and endpoint order are identified correctly."),
        ("14. Dot product", "The dot product of vectors a and b is a·b = |a||b|cosθ and is a scalar. In components, multiply corresponding components and add them."),
        ("15. Perpendicular vectors", "Two non-zero vectors are perpendicular when their dot product is zero. This provides a convenient algebraic test for right angles."),
        ("16. Projection", "The scalar projection of one vector onto another measures how much of one vector acts in the direction of the other. It is closely related to the dot product and cosine of the included angle."),
        ("17. Cross product", "The cross product a×b produces a vector perpendicular to both a and b. Its magnitude is |a||b|sinθ, and its direction follows the right-hand rule."),
        ("18. Area using cross product", "The magnitude of a×b gives the area of the parallelogram formed by a and b. Half of that magnitude gives the area of the triangle formed by the same two vectors."),
        ("19. Direction cosines", "For a vector in three dimensions, its direction cosines are the cosines of the angles it makes with the positive coordinate axes. They satisfy l²+m²+n²=1 for a unit direction vector."),
        ("20. Equation of a line", "A vector equation of a line can be written as r = a + λb, where a is a point on the line, b gives its direction and λ is a scalar parameter."),
        ("21. Coplanarity", "Vectors or points are coplanar when they lie in the same plane. In three dimensions, scalar triple products provide a standard algebraic test for coplanarity."),
        ("22. Worked example", "For a = 2i+3j and b = i-j, a+b = 3i+2j and a·b = 2(1)+3(-1) = -1. The first result is a vector; the second is a scalar."),
        ("23. Common mistakes", "Do not add magnitudes when directions differ, and do not confuse dot and cross products. Check whether the required answer should be a scalar or a vector before choosing the operation."),
        ("24. Exam strategy", "Write vectors in component form when possible, state the relevant formula, substitute carefully and keep i, j and k components separate until the final simplification."),
        ("25. Quick revision", "Remember magnitude, unit vectors, components, addition/subtraction, dot product, perpendicularity, cross product, line equations and the distinction between scalar and vector results."),
    ],
}


def _expanded_generic_notes(topic, subject):
    """Detailed fallback that teaches the learner about the requested topic without
    pretending to know syllabus-specific facts that are not in the local knowledge pack.
    It never asks the learner to write the notes themselves.
    """
    t = topic.strip()
    return [
        ("1. Topic identity", f"{t} is the selected learning topic in {subject}. Begin by identifying what the topic describes, what kind of questions use it, and how it connects to the surrounding chapter."),
        ("2. Core idea", f"The central revision goal for {t} is to understand the concept before memorising terminology. Look for the main relationship, process, structure or rule that explains the topic."),
        ("3. Important terms", f"Separate the key terms used in {t} into definitions, quantities, symbols, conditions and examples. Similar-looking terms should not be treated as synonyms unless the textbook explicitly defines them that way."),
        ("4. Definitions", f"A strong definition of {t} should state what the term means and, where relevant, the condition that makes the definition valid. Use the exact wording required by the learner's textbook for board-specific answers."),
        ("5. Symbols and notation", f"Record the symbols, units and notation associated with {t}. In numerical questions, distinguish a physical quantity from its numerical value and unit."),
        ("6. Main principle", f"Most questions on {t} can be approached by first identifying the governing principle or rule. Do not select a formula merely because it contains familiar symbols; check the conditions under which it applies."),
        ("7. Preconditions", f"Before applying a rule to {t}, check assumptions, definitions and special conditions. A correct formula used under the wrong conditions can still produce an incorrect answer."),
        ("8. Classification", f"If {t} has types, cases or categories, distinguish them by their defining properties. Classification questions are often easier when the defining condition is written next to each type."),
        ("9. Relationships", f"Connect the major ideas in {t} rather than revising them as isolated facts. Ask what changes when one quantity, condition or part of the system changes."),
        ("10. Formula or rule", f"Write the standard formula or rule for {t} exactly as given in the relevant syllabus or textbook. Rearrange it only after identifying the quantity that is required."),
        ("11. Units", f"Check the units used in {t}. Convert prefixes and mixed units before substitution, and make sure the final unit corresponds to the quantity requested."),
        ("12. Diagram or representation", f"A diagram, graph, flow chart or symbolic representation can make {t} easier to understand. Label known quantities and directions before interpreting the representation."),
        ("13. Standard question pattern", f"For a typical {t} problem, identify the given information, state what is required, select the applicable principle, substitute or reason step by step, and then check the result."),
        ("14. Worked-solution structure", f"A complete solution for {t} should show the relevant definition or law, the values or observations used, intermediate reasoning, the final answer and a short verification."),
        ("15. Interpretation", f"Do not stop at the numerical or symbolic result in {t}. Interpret what the answer means, including its direction, sign, magnitude, category or physical/grammatical significance when relevant."),
        ("16. Graphs and trends", f"If {t} is represented graphically, identify the axes, units, trend, slope or relevant regions before drawing conclusions. Do not infer a relationship from appearance alone when a scale or formula is provided."),
        ("17. Applications", f"Understanding {t} is stronger when you can connect the concept to a standard textbook application. Applications should illustrate the concept rather than replace its definition."),
        ("18. Common misconceptions", f"For {t}, separate the central definition from examples and shortcuts. A memorised pattern can fail when a question changes its wording or conditions."),
        ("19. Common calculation errors", f"Typical checks for {t} include signs, powers, brackets, copied values, unit conversions and arithmetic. Re-read the original question after obtaining the answer."),
        ("20. Theory-answer structure", f"For a theory question on {t}, use a concise definition followed by the governing principle, explanation, relevant condition and an example or consequence where appropriate."),
        ("21. Comparison questions", f"When comparing two ideas related to {t}, compare them using the same criteria: definition, condition, formula, behaviour, application or limitation. Avoid mixing unrelated properties."),
        ("22. Exam checkpoints", f"Before submitting a {t} answer, verify that every requested part is answered, the notation is clear, units are present where needed and the method matches the question's conditions."),
        ("23. One-minute revision", f"Recall the definition of {t}, three key terms, the main rule or relationship, one standard application and one common mistake without looking at the page."),
        ("24. Final review", f"A reliable revision of {t} should combine understanding, recall and application. Use the detailed notes first, then a fresh practice set and finally a short self-check."),
    ]

'''
s=s.replace(marker,insert+marker)
old='''    data = RESOURCE_LIBRARY.get(key, _generic_resource(topic, resource["subject"]))\n    if key in RESOURCE_ENHANCEMENTS:\n        data = dict(data)\n        data.update(RESOURCE_ENHANCEMENTS[key])\n    return data\n'''
new='''    data = RESOURCE_LIBRARY.get(key, _generic_resource(topic, resource["subject"]))\n    if key in RESOURCE_ENHANCEMENTS:\n        data = dict(data)\n        data.update(RESOURCE_ENHANCEMENTS[key])\n    # Notes are always expanded to a full revision guide. This also fixes\n    # previously-generated/unknown topics without changing the resource catalog.\n    data = dict(data)\n    data["sections"] = DETAILED_NOTES.get(key, _expanded_generic_notes(topic, resource["subject"]))\n    return data\n'''
assert old in s
s=s.replace(old,new)
p.write_text(s,encoding='utf-8')
print('patched',p)
